certificate/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('cert_list', views.CertificateListView.as_view(), name='cert_list' ),
    path('cert_detail/<int:pk>', views.CertificateDetailView.as_view(), name='cert_detail' ),
    path('cert_create', views.CertificateCreateView.as_view(), name= 'cert_create' ),
    path('cert_update/<int:pk>', views.CertificateUpdateView.as_view(), name= 'cert_update'),
    path('cert_delete/<int:pk>', views.CertificateDeleteView.as_view(), name='cert_delete'),

]

make/urls.py
from django.urls import path
from . import views

urlpatterns = [


path('make/', views.MakeList.as_view(), name='make_list' ),
path('make/detail/<int:pk>', views.MakeDetail.as_view(), name='makedetail' ),
path('make/create', views.CreateMakeView.as_view(), name= 'createmake' ),
path('make/update/<int:pk>', views.UpdateMakeView.as_view(), name= 'updatemake'),
path('make/delete/<int:pk>', views.DeleteMakeView.as_view(), name='deletemake'),

]

masterinstrument/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.contrib import admin


urlpatterns = [
    path('', views.HomeView.as_view(),name='dashboard'),
    # path('login', views.LoginPageView.as_view(),name='login'),
    path('list', views.MasterInstrumentList.as_view(), name='masterinstrument_list' ),
    path('detail/<int:pk>', views.MasterInstrumentDetail.as_view(), name='masterinstrumentdetail' ),
    path('create', views.CreateMasterInstrumentView.as_view(), name= 'createmasterinstrument' ),
    path('update/<int:pk>', views.UpdateMasterInstrumentView.as_view(), name= 'updatemasterinstrument'),
    path('delete/<int:pk>', views.DeleteMasterInstrumentView.as_view(), name='deletemasterinstrument'),


    path('type/', views.MasterInstrumentTypeList.as_view(), name='masterinstrumenttype_list' ),
    path('type/detail/<int:pk>', views.MasterInstrumentTypeDetail.as_view(), name='masterinstrumenttypedetail' ),
    path('type/create', views.CreateMasterInstrumentTypeView.as_view(), name= 'createmasterinstrumenttype' ),
    path('type/update/<int:pk>', views.UpdateMasterInstrumentTypeView.as_view(), name= 'updatemasterinstrumenttype'),
    path('type/delete/<int:pk>', views.DeleteMasterInstrumentTypeView.as_view(), name='deletemasterinstrumenttype'),


    path('certificate', views.MasterInstrumentCertificateList.as_view(), name='masterinstrumentcertificate_list' ),
    path('certificate/detail/<int:pk>', views.MasterInstrumentCertificateDetail.as_view(), name='masterinstrumentcertificatedetail' ),
    path('certificate/create', views.CreateMasterInstrumentCertificateView.as_view(), name= 'createmasterinstrumentcertificate' ),
    path('certificate/update/<int:pk>', views.UpdateMasterInstrumentCertificateView.as_view(), name= 'updatemasterinstrumentcertificate'),
    path('certificate/delete/<int:pk>', views.DeleteMasterInstrumentCertificateView.as_view(), name='deletemasterinstrumentcertificate'),



    path('ajax/load-makes/', views.load_makes, name='ajax_load_makes'),
    path('ajax/load-models/', views.load_models, name='ajax_load_models'),

    path('image_upload', image_view, name = 'image_upload'),
    path('success', success, name = 'success'),

    path('certificate/', views.CertificateListView.as_view(),name='certificate'),

    




]

nabl_final1/urls.py
from django.contrib import admin
from django.urls import path,include
from masterinstrument import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('masterinstrument.urls')),
    path('make/', include('make.urls')),
    path('model/', include('model.urls')),
    path('location/', include('location.urls')),
    path('unit/', include('unit.urls')),
    path('condition/', include('condition.urls')),
    path('calibration_frequency/', include('calibration_frequency.urls')),
    path('parameter_calibrated/', include('parameter_calibrated.urls')),
    path('contact/', include('contact.urls')),
    path('uuc_info/', include('uuc_info.urls')),
    path('job_info/', include('job_info.urls')),
    path('testing_info/', include('testing_info.urls')),
    path('certificate/', include('certificate.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

certificate/models.py
from django.db import models

# Create your models here.

class Certificate(models.Model):
    inst_job_id = models.ForeignKey('testing_info.TestingInfo', on_delete=models.CASCADE)
    cert_number = models.CharField(max_length=200)
    cert_date = models.DateField()
    valid_date = models.DateField()
    issue_date = models.DateField()
    client = models.ForeignKey('contact.organization', on_delete=models.CASCADE)


    def __str__(self):
        return self.cert_number

masterinstrument/models.py
from django.db import models

# Create your models here.

class MasterInstrumentType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)

class MasterInstrument(models.Model):
    master_name = models.ForeignKey('MasterInstrumentType', on_delete=models.CASCADE)
    master_serialno = models.CharField(max_length=200,null=True)
    master_idno = models.CharField(max_length=200,null=True)
    range = models.CharField(max_length=200,null=True)
    inservice_date = models.DateField(null=True)
    inservice = models.BooleanField(default=False)
    make = models.ForeignKey('make.Make',on_delete=models.CASCADE)
    model = models.ForeignKey('model.Model',on_delete=models.CASCADE)
    least_count = models.FloatField(max_length=200,default="")
    resolution = models.FloatField(max_length=200,default="")
    initial_trac = models.CharField(max_length=200,default="")
    acceptance_criteria = models.CharField(max_length=200,default="")
    purchase_from = models.CharField(max_length=200,default="")
    purchase_order = models.CharField(max_length=200,default="")
    purchase_date = models.DateField(null=True)
    date_of_receipt = models.DateField(null=True)
    condition_of_receipt = models.CharField(max_length=200, null=True)
    date_of_inspection = models.DateField(null=True)
    software_details = models.CharField(max_length=200,default="")
    software_idno = models.CharField(max_length=200,default="")
    software_inservice = models.CharField(max_length=200,default="")
    manufacture_instruction = models.CharField(max_length=200,default="")
    national_international_standerd = models.CharField(max_length=200,default="")
    accuracy = models.FloatField(max_length=200,null=True)
    current_inst_condition = models.ForeignKey('condition.Condition',on_delete=models.CASCADE, null=True)
    amount = models.FloatField(max_length=200,null=True)
    parameter_calibrated = models.ForeignKey('parameter_calibrated.ParameterCalibrated',on_delete=models.CASCADE, null=True)
    referance_standard = models.CharField(max_length=200, null=True)
    ext_calibration_agency = models.CharField(max_length=200, null=True)
    cal_frequency = models.ForeignKey('calibration_frequency.CalibrationFrequency',on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.master_name)

class MasterCertificate(models.Model):
    master_id = models.ForeignKey('MasterInstrumentType', on_delete=models.CASCADE, null=True)
    certificate_no = models.CharField(max_length=200)
    ulr_no = models.CharField(max_length=200,null=True)
    uncertainity = models.FloatField(blank=True,default=1)
    issue_date = models.DateField()
    exp_date = models.DateField()
    review_of_record = models.BooleanField(default=False)
    active_status = models.BooleanField(default=False)
    image = models.ImageField(null=True,blank=True)

    def __Str__(self):
        return str(self.master_id)

certificate/forms.py
from django import forms
from certificate.models import Certificate

class DateInput(forms.DateInput):
    input_type = 'date'

class CertForm(forms.ModelForm):

    class Meta:
        model = Certificate
        fields = ('inst_job_id','cert_number','cert_date','valid_date','issue_date','client')
        labels = {
        'inst_job_id': 'Job Id',
        'cert_number': 'Certificate Number',
        'cert_date': 'Certificate Date',
        'valid_date': 'Validity Date',
        'issue_date': 'Issue Date',
        'client': 'Client',
        }
        widgets = {
        'cert_date': DateInput(),
        'valid_date': DateInput(),
        'issue_date': DateInput()
        }

certificate/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from . models import Certificate
from .forms import CertForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User



class CertificateListView(ListView):
    context_object_name = 'cert_list'
    model = Certificate
    template_name = 'certificate/cert_list.html'


class CertificateDetailView(DetailView):
	context_object_name = 'cert_detail'
	model = Certificate
	template_name = 'certificate/cert_detail.html'


class CertificateCreateView(CreateView):
	model = Certificate
	form_class = CertForm
	template_name = 'certificate/cert_form.html'
	success_url = reverse_lazy('cert_list')



class CertificateUpdateView(UpdateView):
	model = Certificate
	form_class = CertForm
	template_name = 'certificate/cert_form.html'
	success_url = reverse_lazy('cert_list')


class CertificateDeleteView(DeleteView):
	model = Certificate
	template_name = 'certificate/cert_confirm_delete.html'
	success_url = reverse_lazy('cert_list')

masterinstrument/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from . models import MasterInstrument,MasterCertificate,MasterInstrumentType
from .forms import MasterInstrumentForm,MasterInstrumentTypeForm,MasterInstrumentCertificateForm,MasterInstrumentCertificateUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from model.models import Model
from make.models import Make
from contact.models import *
from condition.models import Condition
from parameter_calibrated.models import ParameterCalibrated
from calibration_frequency.models import CalibrationFrequency
from make.forms import MakeForm
from model.forms import ModelForm
from condition.forms import ConditionForm
from parameter_calibrated.forms import ParameterCalibratedForm
from calibration_frequency.forms import CalibrationFrequencyForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import *
from testing_info.models import TestingInfo
from testing_info.forms import TestingInfoForm
from certificate.models import Certificate



class HomeView(TemplateView):
	template_name = 'masterinstrument/dashboard.html'

# class LoginPageView(TemplateView):
# 	template_name = 'masterinstrumen/login.html'


# masterinstrument

class MasterInstrumentList(ListView):
	model = MasterInstrument
	template_name = 'masterinstrument/masterinstrument_list.html'

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user


class MasterInstrumentDetail(DetailView):
	context_object_name = 'mi_detail'
	model = MasterInstrument
	template_name = 'masterinstrument/masterinstrument_detail.html'

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class CreateMasterInstrumentView(LoginRequiredMixin,CreateView):
	model = MasterInstrument
	form_class = MasterInstrumentForm
	success_url = reverse_lazy('masterinstrument_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class UpdateMasterInstrumentView(LoginRequiredMixin,UpdateView):
	model = MasterInstrument
	form_class = MasterInstrumentForm
	success_url = reverse_lazy('masterinstrument_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class DeleteMasterInstrumentView(LoginRequiredMixin,DeleteView):
	model = MasterInstrument
	success_url = reverse_lazy('masterinstrument_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user


# MasterInstrumentType

class MasterInstrumentTypeList(ListView):
	model = MasterInstrumentType
	template_name = 'masterinstrument/masterinstrument_type_list.html'
	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class MasterInstrumentTypeDetail(DetailView):
	context_object_name = 'mit_detail'
	model = MasterInstrumentType
	template_name = 'masterinstrument/masterinstrument_type_detail.html'

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class CreateMasterInstrumentTypeView(LoginRequiredMixin,CreateView):
	model = MasterInstrumentType
	form_class = MasterInstrumentTypeForm
	success_url = reverse_lazy('masterinstrumenttype_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user


class UpdateMasterInstrumentTypeView(LoginRequiredMixin,UpdateView):
	model = MasterInstrumentType
	form_class = MasterInstrumentTypeForm
	success_url = reverse_lazy('masterinstrumenttype_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class DeleteMasterInstrumentTypeView(LoginRequiredMixin,DeleteView):
	model = MasterInstrumentType
	success_url = reverse_lazy('masterinstrumenttype_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user


# Master Instrument Certificate

class MasterInstrumentCertificateList(ListView):
	model = MasterCertificate
	template_name = 'masterinstrument/masterinstrumentcertificate_list.html'

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class MasterInstrumentCertificateDetail(DetailView):
	context_object_name = 'mic_detail'
	model = MasterCertificate
	template_name = 'masterinstrument/masterinstrumentcertificate_detail.html'

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class CreateMasterInstrumentCertificateView(CreateView):
	model = MasterCertificate
	form_class = MasterInstrumentCertificateForm
	success_url = reverse_lazy('masterinstrumentcertificate_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user


class UpdateMasterInstrumentCertificateView(UpdateView):
	model = MasterCertificate
	form_class = MasterInstrumentCertificateForm
	success_url = reverse_lazy('masterinstrumentcertificate_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user

class DeleteMasterInstrumentCertificateView(LoginRequiredMixin,DeleteView):
	model = MasterCertificate
	success_url = reverse_lazy('masterinstrumentcertificate_list')

	# def username(request):
	# 	user = User.objects.get(username=request.user.username)
	# 	return user


	####################################(Certificate)#########################################


class CertificateListView(ListView):
	context_object_name = 'certificate_list'
	model = TestingInfo
	queryset = TestingInfo.objects.all()
	template_name = 'masterinstrument/certificate.html'

	def get_context_data(self, **kwargs):
		context = super(CertificateListView, self).get_context_data(**kwargs)
		context['make'] = Make.objects.all()
		context['model'] = Model.objects.all()
		context['organization'] = organization.objects.all()
		context['certificate'] = Certificate.objects.all()
		context['condition'] = Condition.objects.all()
		

		return context





def load_models(request):
    make_id = request.GET.get('make')
    models = Model.objects.filter(make_id=make_id).order_by('model_name')
    return render(request, 'masterinstrument/model_dropdown_list_options.html', {'models': models})


def load_makes(request):
    master_name_id = request.GET.get('master_name')
    makes = Make.objects.filter(master_name_id=master_name_id).order_by('make_name')
    return render(request, 'masterinstrument/make_dropdown_list_options.html', {'makes': makes})



def success(request):
    return HttpResponse('successfully uploaded')

def image_view(request):

    if request.method == 'POST':
        form = MasterCertificateForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = MasterCertificateForm()
    return render(request, 'mastercertificate_form.html', {'form' : form})

masterinstrument/templates/masterinstrument/dashboard.html
{% extends "masterinstrument/base.html" %}

{% block content %}

<div class="container">
  <div class="jumbotron">
    <h2 style="text-align: center;">WELCOME TO KENABL</h2>

  </div>

</div>


{% endblock %}

masterinstrument/templates/masterinstrument/images.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Certificate</title>
</head>
<body>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>

masterinstrument/templates/masterinstrument/mastercertificate_form.html
{% extends "masterinstrument/base.html"%}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <div class="jumbotron">


  	<h1 style="text-align:center">Master Instrument Certificate</h1>
  	<p></p>



  			<form method="POST">
  			{% csrf_token %}
        <div class="row">
          <div class="col-md-12">
              {{form.master_id|as_crispy_field}}
          </div>
          <div class="col-md-12">
              {{form.uncertainity|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.certificate_no|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.ulr_no|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.issue_date|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.exp_date|as_crispy_field}}
          </div>
          <div class="col-md-3">
                {{form.review_of_record|as_crispy_field}}
            </div>
            <div class="col-md-3">
                {{form.active_status|as_crispy_field}}
            </div>
            <div class="col-md-3">
                {{form.image|as_crispy_field}}
            </div>



        <div class="col-md-6">
            <button type="submit" class="btn btn-success btn-block btn-lg" >
                Save</button>
        </div>
        <div class="col-md-6">
            <a href="{% url 'masterinstrumentcertificate_list' %}" class="btn btn-secondary btn-block btn-lg" style="background-color:gray">
                 Back
            </a>
        </div>
        </div>

  	</div>
	</div>

{% endblock %}

masterinstrument/templates/masterinstrument/masterinstrument_confirm_delete.html
{% extends "masterinstrument/base.html"%}

{% block content %}
<div class="container">


<div class="jumbotron">
  <div class="text-center">
    <form action="" method="post">
      {% csrf_token %}
    <h2>  <p>Are you sure you want to delete "{{ object }}"?</p> </h2>
      <input class='btn btn-danger' type="submit" value="Confirm"/>
      <a href="{% url 'masterinstrument_list' %}" class="btn btn-secondary">Back</a>

    </form>
  </div>
</div>
</div>
{% endblock %}

masterinstrument/templates/masterinstrument/masterinstrument_detail.html
{% extends "masterinstrument/base.html"%}

{% block content %}
<div class="container">


<div class="jumbotron">

<div class="text-center">
<h3 class="grayc">Asset Name : {{mi_detail.master_name}}</h3>
</div>

<p></p>

<div class="container">

  <table class="table table-bordered">
    <thead class="thead-dark">
  <tr>
    <th scope="col">Serial No</th>
    <th scope="col">Id No</th>
    <th scope="col">Make</th>
    <th scope="col">Model</th>
    <th scope="col">Range</th>
    <th scope="col">Least Count</th>
    <th scope="col">Date Of Place Inservice</th>
    <th scope="col">Master Instrument Type</th>

  </tr>
</thead>
<tbody>
  <tr>
    <td>{{mi_detail.master_serialno}}</td>
    <td>{{mi_detail.master_idno}}</td>
    <td>{{mi_detail.make}}</td>
    <td>{{mi_detail.model}}</td>
    <td>{{mi_detail.range}}</td>
    <td>{{mi_detail.least_count}}</td>
    <td>{{mi_detail.inservice_date}}</td>
    <td>{{mi_detail.master_name.name}}</td>

  </tr>
</tbody>
</table>
<p></p>
<div class="text-center">
  <a href="{% url 'updatemasterinstrument' pk=mi_detail.pk  %}" class="btn btn-primary">Update</a>
  <a href="{% url 'deletemasterinstrument' pk=mi_detail.pk  %}" class="btn btn-danger">Delete</a>
  <a href="{% url 'masterinstrument_list' %}" class="btn btn-secondary">Back To List</a>

</div>
</div>
</div>
{% endblock %}

masterinstrument/templates/masterinstrument/masterinstrument_form.html
{% extends "masterinstrument/base.html"%}
{% load crispy_forms_tags %}
{% block content %}




<div class="container">
  <div class="jumbotron">
    <h1 style="text-align:center">Master Instrument</h1>
    <p></p>
    <p></p>
    <div class="row">

        <form method="POST" id="MasterInstrumentForm" data-models-url="{% url 'ajax_load_models' %}" data-makes-url="{% url 'ajax_load_makes' %}" novalidate>
        {% csrf_token %}

        <div class="row">
          <div class="col-md-12" id="mastername">
              {{form.master_name|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.master_serialno|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.master_idno|as_crispy_field}}
          </div>
          <div class="col-md-6" id="make">
              {{form.make|as_crispy_field}}
          </div>
          <div class="col-md-6" id="model">
              {{form.model|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.range|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.least_count|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.accuracy|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.inservice_date|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.resolution|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.initial_trac|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.acceptance_criteria|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.current_inst_condition|as_crispy_field}}
          </div>

        <h3 class="col-md-12"><p class="col-md-12">Purchase Details</p></h3>

          <div class="col-md-12">
              {{form.purchase_from|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.purchase_order|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.purchase_date|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.amount|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.date_of_receipt|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.condition_of_receipt|as_crispy_field}}
          </div>
          <div class="col-md-3">
              {{form.date_of_inspection|as_crispy_field}}
          </div>

          <h3 class="col-md-12"><p class="col-md-12">Software Details</p></h3>

          <div class="col-md-4">
              {{form.software_details|as_crispy_field}}
          </div>
          <div class="col-md-4">
              {{form.software_idno|as_crispy_field}}
          </div>
          <div class="col-md-4">
              {{form.software_inservice|as_crispy_field}}
          </div>

          <h3 class="col-md-12"><p class="col-md-12">Instructions For Operation</p></h3>

          <div class="col-md-6">
              {{form.manufacture_instruction|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.national_international_standerd|as_crispy_field}}
          </div>

          <h3 class="col-md-12"><p class="col-md-12">Calibration Requirement</p></h3>

          <div class="col-md-6">
              {{form.parameter_calibrated|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.referance_standard|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.ext_calibration_agency|as_crispy_field}}
          </div>
          <div class="col-md-6">
              {{form.cal_frequency|as_crispy_field}}
          </div>



      </div>

      <!-- <table>
        {{ form.as_table }}
      </table> -->

        <p>	</p>
        <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg" >
                Save</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'masterinstrument_list' %}" class="btn btn-secondary btn-block btn-lg" style="background-color:gray">
                 Back
            </a>
        </div>
    </div>

      </form>


      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_make").change(function () {
          var url = $("#MasterInstrumentForm").attr("data-models-url");
          var makeId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'make': makeId
            },
            success: function (data) {
              $("#id_model").html(data);
            }
          });

        });
      </script>

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_mastername").change(function () {
          var url = $("#MasterInstrumentForm").attr("data-makes-url");
          var masterId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'master_name': masterId
            },
            success: function (data) {
              $("#id_make").html(data);
            }
          });

        });
      </script>




     </div>
      <div class="col-md-3"></div>
    </div>
</div>



</div>

{% endblock %}

masterinstrument/templates/masterinstrument/masterinstrumentcertificate_list.html
{% extends "masterinstrument/base.html"%}
{% load crispy_forms_tags %}

{% block content %}
<p></p>
<p></p>
<div class="container">
  <div class="jumbotron">
 <div>
    <h2 class="text-center">Master Instrument Certificates</h2>
</div>

<p></p>
    <div class="container">

    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Master Instrument Certificate</th>
          <th scope="col">Due Date</th>
          <th scope="col">Serial No</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>

        </tr>
      </thead>
    <p></p>

{% for mic in mastercertificate_list %}


    <tbody>
      <tr>

        <td><a href="{% url 'masterinstrumentcertificatedetail' pk=mic.pk %}">{{mic.master_id}}</a></td>
        <td>{{mic.exp_date}}</td>
        <td>{{mic.master_id.master_serialno}}</td>
        <td><a href="{% url 'updatemasterinstrumentcertificate' pk=mic.pk %}"><i class="fas fa-edit"></a></i></td>
        <td><a href="{% url 'deletemasterinstrumentcertificate' pk=mic.pk %}"><i class="fas fa-trash-alt"></a></i></td>

      </tr>
    </tbody>

    <p></p>

</div>

{% endfor %}
</table>
<p></p>
<p></p>

<div class="text-center">
    <a class="btn btn-success" href="{% url 'createmasterinstrumentcertificate' %}">Create MasterInstrumentCertificate</a>
</div>
</div>
</div>

{% endblock %}

masterinstrument/templates/masterinstrument/model_dropdown_list_options.html
<option value="">---------</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.model_name }}</option>
{% endfor %}